name: Jim Cadden
url: jmcadden.github.io
title: Jim Cadden
email: james.cadden@gmail.com 
tagline: 'has his very own tagline'
highlighter: rouge
exclude: [vendor]
timezone: America/New_York
permalink:           pretty
description:         'Jim is a PhD canidate in Computer Science <a href="">Boston University</a> under the advisement of <a href="">Jonathan Appavoo</a>. Jim is a member of the SESA (scalable systems) research group and works closley with <a href="">Orran Krieger</a> and the <a href="">Massachusettes Open Cloud</a>.</br></br>
Research interests include distributed systems, cloud computing, virtualization and unikernels.'
url:                 https://jmcadden.github.io
baseurl:             ''
paginate:            5
gems: [jekyll-paginate]
