name: Jim Cadden
url: jmcadden.github.io
title:  "Jim Cadden's Homepage"
email: james.cadden@gmail.com 
tagline: "Jim Cadden's Homepage"
indextitle: 'Latest Posts & Updates'
highlighter: rouge
exclude: [vendor]
timezone: America/New_York
permalink: pretty
#description: ''
description: 'Jim Cadden, Ph.D. candidate of Computer Science at <a href="http://www.bu.edu/cs/">Boston University</a>. <div id="my-photo"></div> My research focuse is on system software architectures for datacenters / cloud computing. Beyond, I am into rock climbing, pop-philosophy, and vintage soul music.'
    
url:  'https://jmcadden.github.io'
baseurl:    ''
paginate:   5
gems: [jekyll-paginate]
