name: Jim Cadden
url: jmcadden.github.io
title:  "Jim Cadden's Homepage"
email: james.cadden@gmail.com 
tagline: "Jim Cadden's Homepage"
indextitle: 'All Posts'
highlighter: rouge
exclude: [vendor]
timezone: America/New_York
permalink: pretty
#description: ''
description: 'Jim Cadden is Ph.D. candidate in Computer Science studying at <a href="http://www.bu.edu/cs/">Boston University</a>. <br/><br/>His research focuses on system architectures for datacenters / cloud computing platforms. Additional interests include rock climbing, pop-philosophy, and vintage soul music.'
    
url:  'https://jmcadden.github.io'
baseurl:    ''
paginate:   5
gems: [jekyll-paginate]
