title: "James M Cadden"
timezone: America/New_York
permalink: pretty
exclude: [vendor]
url:  'https://jmcadden.github.io'
baseurl:    ''
highlighter: rouge
markdown: kramdown
collections:
  slides:
    permalink: slides/:path/
    output: true
defaults:
  -
    scope:
      path: ''
      type: 'slides'
    values:
      layout: 'slide'
