name: Jim Cadden
url: jmcadden.github.io
title: Jim Cadden
email: james.cadden@gmail.com 
tagline: ''
indextitle: 'All Posts'
highlighter: rouge
exclude: [vendor]
timezone: America/New_York
permalink:           pretty
description:         'Jim is a PhD canidate in Computer Science at <a href="http://www.bu.edu/cs/">Boston University</a> under the advisement of <a href="https://www.cs.bu.edu/~jappavoo/">Jonathan Appavoo</a> and <a href="http://www.bu.edu/cci/okrieg/">Orran Krieger</a>. </br>Jim is a member of the <a href="http://sesa.github.io/">SESA research group at BU</a> and a close associate of the <a href="http://www.bu.edu/hic/research/massachusetts-open-cloud/">Massachusettes Open Cloud</a>.</br></br>
Jim`s research interests include <ul><li>distributed systems</li><li>cloud computing</li><li>virtualization</li><li>microkernels</li></ul>'
url:                 https://jmcadden.github.io
baseurl:             ''
paginate:            5
gems: [jekyll-paginate]
